var child = [
  { 'dupe': false, 'type': 128, 'name': '3srbKOG586LnYME4GvNhduDIof3ggnPC4cjVctM3SwEBX6ccoEPV0uEIPHjwUMMo', 'dir': 'c0', 'linked': 0, 'url': 'http://localhost:8000/register DATA:csrfmiddlewaretoken=3srbKOG586LnYME4GvNhduDIof3ggnPC4cjVctM3SwEBX6ccoEPV0uEIPHjwUMMo&username=Smith&email=skipfish@example.com&password1=skipfish&password2=skipfish', 'fetched': true, 'code': 200, 'len': 2331, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0xff7ed694 },
  { 'dupe': true, 'type': 128, 'name': '6rh8kY2dI0BYOZ1mNdkEpztulXzVYmjp7b9SMD8bsqucNjzuvmmiczuuMpPbCLgb', 'dir': 'c1', 'linked': 0, 'url': 'http://localhost:8000/register DATA:csrfmiddlewaretoken=6rh8kY2dI0BYOZ1mNdkEpztulXzVYmjp7b9SMD8bsqucNjzuvmmiczuuMpPbCLgb&username=Smith&email=skipfish@example.com&password1=skipfish&password2=skipfish', 'fetched': true, 'code': 200, 'len': 2331, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xff7ed694 },
  { 'dupe': true, 'type': 128, 'name': '8I5PoTSDWq4OnEkQXDjfNSYsDPFISJ2z9sXzQyYBGQX2mYSYFMlTASZs4hVYw8Zl', 'dir': 'c2', 'linked': 0, 'url': 'http://localhost:8000/register DATA:csrfmiddlewaretoken=8I5PoTSDWq4OnEkQXDjfNSYsDPFISJ2z9sXzQyYBGQX2mYSYFMlTASZs4hVYw8Zl&username=Smith&email=skipfish@example.com&password1=skipfish&password2=skipfish', 'fetched': true, 'code': 200, 'len': 2331, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xff7ed694 },
  { 'dupe': true, 'type': 128, 'name': 'fZkEp5iYGLKjmdhXPgvOKx9AswYYDEPRgJcoRKoWqbDxlxP5xpxsxxaATYeeh3MD', 'dir': 'c3', 'linked': 0, 'url': 'http://localhost:8000/register DATA:csrfmiddlewaretoken=fZkEp5iYGLKjmdhXPgvOKx9AswYYDEPRgJcoRKoWqbDxlxP5xpxsxxaATYeeh3MD&username=Smith&email=skipfish@example.com&password1=skipfish&password2=skipfish', 'fetched': true, 'code': 200, 'len': 2331, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xff7ed694 },
  { 'dupe': true, 'type': 128, 'name': 'guvuJkd4HkSwur5oeXRvDYyy2ptBGiTJhenebZj2rKLKtLDwW6T9qYzytRJRkHQv', 'dir': 'c4', 'linked': 0, 'url': 'http://localhost:8000/register DATA:csrfmiddlewaretoken=guvuJkd4HkSwur5oeXRvDYyy2ptBGiTJhenebZj2rKLKtLDwW6T9qYzytRJRkHQv&username=Smith&email=skipfish@example.com&password1=skipfish&password2=skipfish', 'fetched': true, 'code': 200, 'len': 2331, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xff7ed694 },
  { 'dupe': true, 'type': 128, 'name': 'hBp3dC37EYuI7DmZDjyUYzXfzzY0uIOgilhNFh95oonW6XU7lsAyLzYf01eg87L2', 'dir': 'c5', 'linked': 0, 'url': 'http://localhost:8000/register DATA:csrfmiddlewaretoken=hBp3dC37EYuI7DmZDjyUYzXfzzY0uIOgilhNFh95oonW6XU7lsAyLzYf01eg87L2&username=Smith&email=skipfish@example.com&password1=skipfish&password2=skipfish', 'fetched': true, 'code': 200, 'len': 2331, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xff7ed694 },
  { 'dupe': true, 'type': 128, 'name': 'kC1tvCQGU2qcmxhUHeREQ6IEod9o4wL6lmTdXhWEEsjqlRP2pnTiD6JEPFpEIVIS', 'dir': 'c6', 'linked': 0, 'url': 'http://localhost:8000/register DATA:csrfmiddlewaretoken=kC1tvCQGU2qcmxhUHeREQ6IEod9o4wL6lmTdXhWEEsjqlRP2pnTiD6JEPFpEIVIS&username=Smith&email=skipfish@example.com&password1=skipfish&password2=skipfish', 'fetched': true, 'code': 200, 'len': 2331, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xff7ed694 },
  { 'dupe': true, 'type': 128, 'name': 'nyJNdsAqdwyl1xRWdNQ5B1XUQYP4Gl3OoiBxF7GoXWrz0Rp4VWSJo1YUhq5kkK0A', 'dir': 'c7', 'linked': 0, 'url': 'http://localhost:8000/register DATA:csrfmiddlewaretoken=nyJNdsAqdwyl1xRWdNQ5B1XUQYP4Gl3OoiBxF7GoXWrz0Rp4VWSJo1YUhq5kkK0A&username=Smith&email=skipfish@example.com&password1=skipfish&password2=skipfish', 'fetched': true, 'code': 200, 'len': 2331, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xff7ed694 },
  { 'dupe': true, 'type': 128, 'name': 'q6Z8TnNmIVPu2j4GN4QbSbvX0yH0X7cWrQRSl2TkslII1DCOvdSPFbwXr0XgBw9I', 'dir': 'c8', 'linked': 0, 'url': 'http://localhost:8000/register DATA:csrfmiddlewaretoken=q6Z8TnNmIVPu2j4GN4QbSbvX0yH0X7cWrQRSl2TkslII1DCOvdSPFbwXr0XgBw9I&username=Smith&email=skipfish@example.com&password1=skipfish&password2=skipfish', 'fetched': true, 'code': 200, 'len': 2331, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xff7ed694 },
  { 'dupe': true, 'type': 128, 'name': 'qBtYEuwgXMxnlB4P3o2c59IZdrsLKPLhrllI69CeHcqBkVCXLx4QS9JZETI1oeI3', 'dir': 'c9', 'linked': 0, 'url': 'http://localhost:8000/register DATA:csrfmiddlewaretoken=qBtYEuwgXMxnlB4P3o2c59IZdrsLKPLhrllI69CeHcqBkVCXLx4QS9JZETI1oeI3&username=Smith&email=skipfish@example.com&password1=skipfish&password2=skipfish', 'fetched': true, 'code': 200, 'len': 2331, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xff7ed694 },
  { 'dupe': true, 'type': 128, 'name': 'RHtE8RLsF4OOJ9LICUXCZrLzCHg5gUazSrloAwRqpuH2ItjQk3ZgMrMz39wlUj7l', 'dir': 'c10', 'linked': 0, 'url': 'http://localhost:8000/register DATA:csrfmiddlewaretoken=RHtE8RLsF4OOJ9LICUXCZrLzCHg5gUazSrloAwRqpuH2ItjQk3ZgMrMz39wlUj7l&username=Smith&email=skipfish@example.com&password1=skipfish&password2=skipfish', 'fetched': true, 'code': 200, 'len': 2331, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xff7ed694 },
  { 'dupe': true, 'type': 128, 'name': 'UdeE9wb4VKP4yw9Ryl369ilQnHB3QR9bVX6oBbh2FaIixQHZgu5KWimQO9Rjug6X', 'dir': 'c11', 'linked': 0, 'url': 'http://localhost:8000/register DATA:csrfmiddlewaretoken=UdeE9wb4VKP4yw9Ryl369ilQnHB3QR9bVX6oBbh2FaIixQHZgu5KWimQO9Rjug6X&username=Smith&email=skipfish@example.com&password1=skipfish&password2=skipfish', 'fetched': true, 'code': 200, 'len': 2331, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xff7ed694 },
  { 'dupe': true, 'type': 128, 'name': 'V4ejyOIHCRAAhAWT49RoG8kiKZuRzPjKWO630tOFmhtOgUu1MiT2t8librK7degw', 'dir': 'c12', 'linked': 0, 'url': 'http://localhost:8000/register DATA:csrfmiddlewaretoken=V4ejyOIHCRAAhAWT49RoG8kiKZuRzPjKWO630tOFmhtOgUu1MiT2t8librK7degw&username=Smith&email=skipfish@example.com&password1=skipfish&password2=skipfish', 'fetched': true, 'code': 200, 'len': 2331, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xff7ed694 },
  { 'dupe': true, 'type': 128, 'name': 'wxuqLznNUEwiTDJbEMV9VbmXxpJYJYrnxhmadetLE4pwSXhjmVXNIbnXYRZenno9', 'dir': 'c13', 'linked': 0, 'url': 'http://localhost:8000/register DATA:csrfmiddlewaretoken=wxuqLznNUEwiTDJbEMV9VbmXxpJYJYrnxhmadetLE4pwSXhjmVXNIbnXYRZenno9&username=Smith&email=skipfish@example.com&password1=skipfish&password2=skipfish', 'fetched': true, 'code': 200, 'len': 2331, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xff7ed694 },
  { 'dupe': true, 'type': 128, 'name': 'xtMoxg79R1Bok22BNjcXbbXXJJ5w6rIOydE8ZVd7BruCjmAJvseBYbYXablMKQFA', 'dir': 'c14', 'linked': 0, 'url': 'http://localhost:8000/register DATA:csrfmiddlewaretoken=xtMoxg79R1Bok22BNjcXbbXXJJ5w6rIOydE8ZVd7BruCjmAJvseBYbYXablMKQFA&username=Smith&email=skipfish@example.com&password1=skipfish&password2=skipfish', 'fetched': true, 'code': 200, 'len': 2331, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xff7ed694 }
];
