# Generated by Django 2.2.7 on 2020-01-04 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0004_auto_20191118_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='message',
            field=models.TextField(default=''),
        ),
    ]
